export const orderList = {
  totalPages: 1,
  totalElements: 2,
  first: true,
  last: true,
  size: 3,
  content: [
    {
      category: '패스트푸드',
      storeName: '버거킹전남대점',
      minimumOrderAmount: 3,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: true,
      price: 11900,
      isCreater: false,
    },
    {
      category: '중식',
      storeName: '스피드반점',
      minimumOrderAmount: 4,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: false,
      price: 12900,
      isCreater: true,
    },
    {
      category: '한식',
      storeName: '한솥도시락',
      minimumOrderAmount: 4,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: false,
      price: 9000,
      isCreater: true,
    },
    {
      category: '일식',
      storeName: '루키초밥',
      minimumOrderAmount: 4,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: false,
      price: 30000,
      isCreater: true,
    },
    {
      category: '일식',
      storeName: '상무초밥',
      minimumOrderAmount: 4,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: false,
      price: 15000,
      isCreater: true,
    },
  ],
  number: 0,
  sort: {
    empty: false,
    unsorted: false,
    sorted: true,
  },
  pageable: {
    pageNumber: 0,
    pageSize: 3,
    sort: {
      empty: false,
      unsorted: false,
      sorted: true,
    },
    offset: 0,
    unpaged: false,
    paged: true,
  },
  numberOfElements: 2,
  empty: false,
};
